# Generated by Django 3.2.7 on 2021-10-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
