# Generated by Django 3.2.7 on 2021-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cup_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
